[bumpver]
current_version = "0.4.2-beta"
version_pattern = "MAJOR.MINOR.PATCH[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"core/settings.py" = [
    "'VERSION': '{version}'"
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
