# Generated by Django 5.1.3 on 2024-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('canceled', 'Canceled'), ('paid', 'Paid'), ('check-in', 'Check-in'), ('check-out', 'Check-out')], default='registered', max_length=20),
        ),
    ]
