# Generated by Django 5.1.3 on 2024-12-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reserve_status'),
        ('rooms', '0004_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='rooms.room'),
        ),
    ]
