# Generated by Django 5.1.3 on 2024-12-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reserve_check_in_before_check_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledreserve',
            old_name='amount',
            new_name='penalty',
        ),
    ]
