# Generated by Django 5.1.3 on 2024-12-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0005_rename_amount_cancelledreserve_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserve')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('created_at'))), name='due_date_after_created_at'), models.CheckConstraint(condition=models.Q(models.Q(('is_paid', False), ('payment_date__isnull', True)), models.Q(('is_paid', True), ('payment_date__isnull', False)), _connector='OR'), name='is_paid_xor_payment_date')],
            },
        ),
    ]
