# Generated by Django 5.1.3 on 2025-01-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reserve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserve'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('created_at'))), name='due_date_after_created_at'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'waiting'), ('status', 'overdue'), _connector='OR'), ('payment_date__isnull', True)), models.Q(('status', 'paid'), ('payment_date__isnull', False)), _connector='OR'), name='is_paid_xor_payment_date'),
        ),
    ]
