# Generated by Django 5.1.3 on 2024-12-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_reservation_bill_reserve'),
        ('reservations', '0005_rename_amount_cancelledreserve_penalty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='is_paid_xor_payment_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='waiting', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'waiting'), ('status', 'overdue'), _connector='OR'), ('payment_date__isnull', True)), models.Q(('status', 'paid'), ('payment_date__isnull', False)), _connector='OR'), name='is_paid_xor_payment_date'),
        ),
    ]
