# Generated by Django 5.1.3 on 2025-01-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='reserve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='reservations.reserve'),
        ),
    ]
