# Generated by Django 5.1.3 on 2025-01-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bill_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('cvv2', models.CharField(max_length=4)),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='payments.bill')),
            ],
        ),
    ]
