# Generated by Django 5.1.3 on 2024-12-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_bill_due_date'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='reserve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserve'),
        ),
    ]
