services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - static_files_volume:/usr/src/app/staticfiles:rw
      - media_files_volume:/usr/src/app/media:rw
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx:1.25
    ports:
      - "12345:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files_volume:/usr/share/nginx/html/static/:ro
      - media_files_volume:/usr/share/nginx/html/media/:ro
    depends_on: 
      web:
        condition: service_healthy


volumes:
  static_files_volume:
  media_files_volume:
