# Generated by Django 5.1.3 on 2024-12-08 14:49

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_guestprofile_address_alter_guestprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Say cheese! Maximum file size allowed is 5MB. Allowed formats: jpg, jpeg, png', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID should be entered in the format: 1234567890. 10 digits allowed', max_length=10, validators=[django.core.validators.RegexValidator(message='National ID should be entered in the format: 1234567890. 10 digits allowed', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number should be entered in the format: +989123456789. 13 digits allowed', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be entered in the format: +989123456789. 13 digits allowed', regex='^\\+98\\d{10}$')]),
        ),
    ]
