name: SonarQube backend

on:
  push:
    branches:
      - master
      - backend
    paths-ignore:
      - 'frontend/**'
      - '.github/**'
      - 'README.md'

env:
  ALLOWED_HOSTS: "127.0.0.1,localhost"
  CSRF_TRUSTED_ORIGINS: "http://127.0.0.1,http://localhost"
  CORS_ALLOWED_ORIGINS: "https://hotel.moeinarabi.ir"
  SECRET_KEY: "something"
  DATABASE_URL: "sqlite:///db.sqlite3"
  DEBUG: "True"

defaults:
  run:
    working-directory: ./backend

jobs:
  analysis:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e py
      - name: Sonar scanning
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=hotel_backend
            -Dsonar.python.version=3.10
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}